AWSTemplateFormatVersion: 2010-09-09
Description: Master template for Max's development environment
  
Parameters:
  VpcCidr:
    Description: Enter the VPC CIDR Block
    Type: String
    ConstraintDescription: Support subnet sizes of /16 to /22 only. i.e. 10.0.0.0/16
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PublicSubnetCIDR:
    Description: Public Subnet CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PublicSubnetCIDR2:
    Description: Public Subnet 2 CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PrivateSubnetCIDR:
    Description: Private Subnet CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PrivateSubnetCIDR2:
    Description: Private Subnet 2 CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network
      Parameters:
        - VpcCidr
        - PublicSubnetCIDR
        - PublicSubnetCIDR2
        - PrivateSubnetCIDR
        - PrivateSubnetCIDR2
    ParameterLabels:
      VpcCidr:
        default: VPC CIDR Block
      PublicSubnetCIDR:
        default: Public Subnet CIDR
      PublicSubnetCIDR2:
        default: Public Subnet 2 CIDR
      PrivateSubnetCIDR:
        default: Private Subnet CIDR
      PrivateSubnetCIDR2:
        default: Private Subnet 2 CIDR  

Resources:
  maxVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcCidr:
          Ref: VpcCidr      
        PublicSubnetCIDR:
          Ref: PublicSubnetCIDR
        PublicSubnetCIDR2:
          Ref: PublicSubnetCIDR2
        PrivateSubnetCIDR:
          Ref: PrivateSubnetCIDR
        PrivateSubnetCIDR2:
          Ref: PrivateSubnetCIDR2
      TemplateURL: https://maxdevenvironment.s3.us-east-2.amazonaws.com/network/main.yaml
      TimeoutInMinutes: '30'
