AWSTemplateFormatVersion: 2010-09-09
Description: VPC Nested Stack for Max's Development Environment
  
Parameters:  
  VpcCidr:
    Description: Enter the VPC CIDR Block
    Type: String
    ConstraintDescription: Support subnet sizes of /16 to /22 only. i.e. 10.0.0.0/16
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PublicSubnetCIDR:
    Description: Public Subnet CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PublicSubnetCIDR2:
    Description: Public Subnet 2 CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PrivateSubnetCIDR:
    Description: Private Subnet CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"

  PrivateSubnetCIDR2:
    Description: Private Subnet 2 CIDR
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"   

Conditions:
  CreateSubnetA:
    Fn::And:
    - Fn::Not:
      - Fn::Equals:
        - Ref: PublicSubnetCIDR
        - ''

    - Fn::Not:
      - Fn::Equals:
        - Ref: PublicSubnetCIDR2
        - ''

    - Fn::Not:
      - Fn::Equals:
        - Ref: PrivateSubnetCIDR
        - ''

    - Fn::Not:
      - Fn::Equals:
        - Ref: PrivateSubnetCIDR2
        - ''        

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network
      Parameters:
      - VpcCidr
      - PublicSubnetCIDR
      - PublicSubnetCIDR2
      - PrivateSubnetCIDR
      - PrivateSubnetCIDR2
    ParameterLabels:
      VpcCidr:
        default: VPC CIDR Block
      PublicSubnetCIDR:
        default: Public Subnet CIDR
      PublicSubnetCIDR2:
        default: Public Subnet 2 CIDR
      PrivateSubnetCIDR:
        default: Private Subnet CIDR
      PrivateSubnetCIDR2:
        default: Private Subnet 2 CIDR  

Resources:
  maxVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: 'default'
      Tags:
        - Key: Name
          Value: max-dev-env-vpc

        - Key: Environment
          Value: Development

  maxPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: maxVpc
      CidrBlock:
        Ref: PublicSubnetCIDR
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: 
              Ref: 'AWS::Region'
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: max-dev-subnet-public
        
        - Key: Network
          Value: Public

        - Key: Environment
          Value: Development

  maxPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: maxVpc
      CidrBlock:
        Ref: PublicSubnetCIDR2
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: 
              Ref: 'AWS::Region'
      MapPublicIpOnLaunch: 'true'              
      Tags:
        - Key: Name
          Value: max-dev-subnet-public-2
        
        - Key: Network
          Value: Public

        - Key: Environment
          Value: Development

  maxPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: maxVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR
      MapPublicIpOnLaunch: 'false'        
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: 
              Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: max-dev-subnet-private
        
        - Key: Network
          Value: Private

        - Key: Environment
          Value: Development                    

  maxPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: maxVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR2
      MapPublicIpOnLaunch: 'false'        
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: 
              Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: max-dev-subnet-private-2
        
        - Key: Network
          Value: Private

        - Key: Environment
          Value: Development 

  maxIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: max-dev-igw

        - Key: Network
          Value: Public

  maxVpcGatewayAttach:
    DependsOn:
      - maxVpc
      - maxIGW
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: maxVpc
      InternetGatewayId:
        Ref: maxIGW

  maxPublicRouteTable:
    DependsOn:
      - maxVpc
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: max-dev-route-public

        - Key: Network
          Value: Public

  maxPublicRoute:
    DependsOn:
      - maxPublicRouteTable
      - maxIGW
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: maxPublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        Ref: maxIGW

  maxPublicSubnetRouteTableAssociation:
    DependsOn:
      - maxPublicSubnet
      - maxPublicRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: maxPublicSubnet
      RouteTableId:
        Ref: maxPublicRouteTable

  maxPublicSubnetRouteTableAssociation2:
    DependsOn:
      - maxPublicSubnet2
      - maxPublicRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: maxPublicSubnet2
      RouteTableId:
        Ref: maxPublicRouteTable        
  
  maxPrivateRouteTable:
    DependsOn:
      - maxVpc
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: max-dev-route-private

        - Key: Network
          Value: Private

  maxPrivateSubnetRouteTableAssociation:
    DependsOn:
      - maxPrivateSubnet
      - maxPrivateRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: maxPrivateSubnet
      RouteTableId:
        Ref: maxPrivateRouteTable

  maxPrivateSubnetRouteTableAssociation2:
    DependsOn:
      - maxPrivateSubnet2
      - maxPrivateRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: maxPrivateSubnet2
      RouteTableId:
        Ref: maxPrivateRouteTable        

  maxPublicSubnetACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn:
      - maxPublicNACL
      - maxPublicSubnet
    Properties: 
      NetworkAclId:
        Ref: maxPublicNACL
      SubnetId:
        Ref: maxPublicSubnet

  maxPublicSubnetACLAssociation2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn:
      - maxPublicNACL
      - maxPublicSubnet2
    Properties: 
      NetworkAclId:
        Ref: maxPublicNACL
      SubnetId:
        Ref: maxPublicSubnet2      

  maxPrivateSubnetACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn:
      - maxPrivateNACL
      - maxPrivateSubnet
    Properties: 
      NetworkAclId:
        Ref: maxPrivateNACL
      SubnetId:
        Ref: maxPrivateSubnet  

  maxPrivateSubnetACLAssociation2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn:
      - maxPrivateNACL
      - maxPrivateSubnet2
    Properties: 
      NetworkAclId:
        Ref: maxPrivateNACL
      SubnetId:
        Ref: maxPrivateSubnet2        

  maxNATGW:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - maxVpcGatewayAttach
    Properties:
      AllocationId:
        Fn::GetAtt:
          - maxNATGWEIP
          - AllocationId
      SubnetId:
        Ref: maxPublicSubnet

  maxNATGWEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 'vpc'

  maxNATRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: maxPrivateRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId:
        Ref: maxNATGW

  maxPrivateNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: 
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: maxPrivateNACL

  maxPublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: 
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: maxPublicNACL

  maxACL1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: maxPrivateNACL

  maxACL3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: 
        Ref: maxPublicNACL        

Outputs:
  VpcId:
    Value:
      Ref: maxVpc
    Description: 'VPC ID for max-dev-env'

  VpcCidr:
    Value:
      Ref: VpcCidr
    Description: 'VPC Cidr address assigned for max-dev-env'

  PublicSubnet:
    Value:
      Ref: maxPublicSubnet
    Description: '1st Public Subnet for max-dev-env'

  PublicSubnet2:
    Value:
      Ref: maxPublicSubnet2
    Description: '2nd Public Subnet for max-dev-env'    

  PrivateSubnet:
    Value:
      Ref: maxPrivateSubnet
    Description: 'Private Subnet for max-dev-env' 

  PrivateSubnet2:
    Value:
      Ref: maxPrivateSubnet2
    Description: 'Private Subnet 2 for max-dev-env' 

  PrivateNACL:
    Value:
      Ref: maxPrivateNACL
    Description: 'Private NACL for max-dev-env'

  PublicNACL:
      Value:
        Ref: maxPublicNACL
      Description: 'Public NACL for max-dev-env'  

  IGW:
    Value:
      Ref: maxIGW
    Description: 'IGW for max-dev-env'   

  NATGW:
    Value:
      Ref: maxNATGW
    Description: 'NAT GW for max-dev-env'   

  EIP:
    Value:
      Ref: maxNATGWEIP
    Description: 'Elastic IP attached for max-dev-env'     