AWSTemplateFormatVersion: 2010-09-09
Description: VPC Nested Stack for Max's Development Environment

Parameters:
  maxVpc:
    Description: The VPC Id of an existing VPC.
    Type: AWS::EC2::VPC::Id

Resources:
  # Network ACL
  maxPrivateNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: 
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: maxPrivateNACL

  maxPublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: 
        Ref: maxVpc
      Tags:
        - Key: Name
          Value: maxPublicNACL

  maxACL1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId:
        Ref: maxPrivateNACL

  maxACL2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: 
        Ref: maxPrivateNACL

  maxACL3:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: 
        Ref: maxPublicNACL

  maxACL4:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: 
        Ref: maxPublicNACL

Outputs:
  PrivateNACL:
    Value:
      Ref: maxPrivateNACL
    Description: 'Private NACL for max-dev-env'

  PublicNACL:
      Value:
        Ref: maxPublicNACL
      Description: 'Public NACL for max-dev-env'  