AWSTemplateFormatVersion: 2010-09-09
Description: VPC Nested Stack for Max's Development Environment

Parameters:

  maxVpc:
    Type:

Resources:
  PublicIngress:
    Type:  AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh access to public
      GroupName: maxdevpublic-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 3389
        ToPort: 3389
        CidrIp: 0.0.0.0/0        
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 3389
        ToPort: 3389
        CidrIp: 0.0.0.0/0                
      Tags:
        - Key: Name
          Value: maxdevpublic-sg
      VpcId:
        Ref: maxVpc

Outputs: